
#ifndef KEYTABLE_START
#define KEYTABLE_START enum class Key : uint16_t {
#endif

#ifndef KEYTABLE_END
#define KEYTABLE_END };
#endif

#ifndef VIRTUALKEY_KEY_MAP
#define VIRTUALKEY_KEY_MAP(x) KT_##x,
#endif

#ifndef VIRTUALKEY_KEY_MAP2
#define VIRTUALKEY_KEY_MAP2(x, y) KT_##x,
#endif
#ifndef NORMALKEY_KEY_MAP
#define NORMALKEY_KEY_MAP(c, d) KT_##c,
#endif

KEYTABLE_START
VIRTUALKEY_KEY_MAP(ESCAPE)
NORMALKEY_KEY_MAP(1, '1')
NORMALKEY_KEY_MAP(2, '2')
NORMALKEY_KEY_MAP(3, '3')
NORMALKEY_KEY_MAP(4, '4')
NORMALKEY_KEY_MAP(5, '5')
NORMALKEY_KEY_MAP(6, '6')
NORMALKEY_KEY_MAP(7, '7')
NORMALKEY_KEY_MAP(8, '8')
NORMALKEY_KEY_MAP(9, '9')
NORMALKEY_KEY_MAP(0, '0')
VIRTUALKEY_KEY_MAP2(MINUS, OEM_MINUS)    // _-on main keyboard
VIRTUALKEY_KEY_MAP2(EQUALS, OEM_PLUS)    // _-on main keyboard
VIRTUALKEY_KEY_MAP(BACK)        // backspace
VIRTUALKEY_KEY_MAP(TAB)
NORMALKEY_KEY_MAP(Q, 'Q')
NORMALKEY_KEY_MAP(W, 'W')
NORMALKEY_KEY_MAP(E, 'E')
NORMALKEY_KEY_MAP(R, 'R')
NORMALKEY_KEY_MAP(T, 'T')
NORMALKEY_KEY_MAP(Y, 'Y')
NORMALKEY_KEY_MAP(U, 'U')
NORMALKEY_KEY_MAP(I, 'I')
NORMALKEY_KEY_MAP(O, 'O')
NORMALKEY_KEY_MAP(P, 'P')
VIRTUALKEY_KEY_MAP2(LBRACKET, OEM_4)
VIRTUALKEY_KEY_MAP2(RBRACKET, OEM_5)
VIRTUALKEY_KEY_MAP(RETURN)    /* Enter on main keyboard */
VIRTUALKEY_KEY_MAP(LCONTROL)
NORMALKEY_KEY_MAP(A, 'A')
NORMALKEY_KEY_MAP(S, 'S')
NORMALKEY_KEY_MAP(D, 'D')
NORMALKEY_KEY_MAP(F, 'F')
NORMALKEY_KEY_MAP(G, 'G')
NORMALKEY_KEY_MAP(H, 'H')
NORMALKEY_KEY_MAP(J, 'J')
NORMALKEY_KEY_MAP(K, 'K')
NORMALKEY_KEY_MAP(L, 'L')
VIRTUALKEY_KEY_MAP2(SEMICOLON, OEM_1)
VIRTUALKEY_KEY_MAP2(APOSTROPHE, OEM_3)
VIRTUALKEY_KEY_MAP2(GRAVE, OEM_2)
VIRTUALKEY_KEY_MAP(LSHIFT)
VIRTUALKEY_KEY_MAP2(BACKSLASH, OEM_5)
NORMALKEY_KEY_MAP(Z, 'Z')
NORMALKEY_KEY_MAP(X, 'X')
NORMALKEY_KEY_MAP(C, 'C')
NORMALKEY_KEY_MAP(V, 'V')
NORMALKEY_KEY_MAP(B, 'B')
NORMALKEY_KEY_MAP(N, 'N')
NORMALKEY_KEY_MAP(M, 'M')
VIRTUALKEY_KEY_MAP2(COMMA, OEM_COMMA)
VIRTUALKEY_KEY_MAP2(PEROID, OEM_PERIOD)
VIRTUALKEY_KEY_MAP2(SLASH, OEM_2)
VIRTUALKEY_KEY_MAP(RSHIFT)
VIRTUALKEY_KEY_MAP(MULTIPLY)    /* * on numeric keypad */
VIRTUALKEY_KEY_MAP(LMENU)    /* left Alt */
VIRTUALKEY_KEY_MAP(SPACE)
VIRTUALKEY_KEY_MAP(CAPITAL)
VIRTUALKEY_KEY_MAP(F1)
VIRTUALKEY_KEY_MAP(F2)
VIRTUALKEY_KEY_MAP(F3)
VIRTUALKEY_KEY_MAP(F4)
VIRTUALKEY_KEY_MAP(F5)
VIRTUALKEY_KEY_MAP(F6)
VIRTUALKEY_KEY_MAP(F7)
VIRTUALKEY_KEY_MAP(F8)
VIRTUALKEY_KEY_MAP(F9)
VIRTUALKEY_KEY_MAP(F10)
VIRTUALKEY_KEY_MAP(F11)
VIRTUALKEY_KEY_MAP(F12)
VIRTUALKEY_KEY_MAP(NUMLOCK)
VIRTUALKEY_KEY_MAP(SCROLL)    /* Scroll Lock */
VIRTUALKEY_KEY_MAP(NUMPAD7)
VIRTUALKEY_KEY_MAP(NUMPAD8)
VIRTUALKEY_KEY_MAP(NUMPAD9)
VIRTUALKEY_KEY_MAP(SUBTRACT)    /* - on numeric keypad */
VIRTUALKEY_KEY_MAP(NUMPAD4)
VIRTUALKEY_KEY_MAP(NUMPAD5)
VIRTUALKEY_KEY_MAP(NUMPAD6)
VIRTUALKEY_KEY_MAP(ADD)    /* + on numeric keypad */
VIRTUALKEY_KEY_MAP(NUMPAD1)
VIRTUALKEY_KEY_MAP(NUMPAD2)
VIRTUALKEY_KEY_MAP(NUMPAD3)
VIRTUALKEY_KEY_MAP(NUMPAD0)
VIRTUALKEY_KEY_MAP(DECIMAL)    /* . on numeric keypad */
VIRTUALKEY_KEY_MAP(OEM_102)    /* <> or \| on RT 102-key keyboard (Non-U.S.) */
VIRTUALKEY_KEY_MAP2(PREVTRACK, MEDIA_PREV_TRACK)
VIRTUALKEY_KEY_MAP2(STOP, MEDIA_STOP)
VIRTUALKEY_KEY_MAP2(NEXTTRACK, MEDIA_NEXT_TRACK)
VIRTUALKEY_KEY_MAP(RCONTROL)
VIRTUALKEY_KEY_MAP2(MUTE, VOLUME_MUTE)
VIRTUALKEY_KEY_MAP2(PLAYPAUSE, MEDIA_PLAY_PAUSE)
VIRTUALKEY_KEY_MAP2(VOLUMEDOWN, VOLUME_DOWN)
VIRTUALKEY_KEY_MAP2(VOLUMEUP, VOLUME_UP)
VIRTUALKEY_KEY_MAP(DIVIDE)    /* / on numeric keypad */
VIRTUALKEY_KEY_MAP(RMENU)    /* right Alt */
VIRTUALKEY_KEY_MAP(PAUSE)
VIRTUALKEY_KEY_MAP(HOME)    /* Home on arrow keypad */
VIRTUALKEY_KEY_MAP(UP)    /* UpArrow on arrow keypad */
VIRTUALKEY_KEY_MAP(PRIOR)    /* PgUp on arrow keypad */
VIRTUALKEY_KEY_MAP(LEFT)    /* LeftArrow on arrow keypad */
VIRTUALKEY_KEY_MAP(RIGHT)    /* RightArrow on arrow keypad */
VIRTUALKEY_KEY_MAP(END)    /* End on arrow keypad */
VIRTUALKEY_KEY_MAP(DOWN)    /* DownArrow on arrow keypad */
VIRTUALKEY_KEY_MAP(NEXT)    /* PgDn on arrow keypad */
VIRTUALKEY_KEY_MAP(INSERT)    /* Insert on arrow keypad */
VIRTUALKEY_KEY_MAP(DELETE)    /* Delete on arrow keypad */
VIRTUALKEY_KEY_MAP(LWIN)    /* Left Windows key */
VIRTUALKEY_KEY_MAP(RWIN)    /* Right Windows key */
VIRTUALKEY_KEY_MAP(APPS)    /* AppMenu key */
VIRTUALKEY_KEY_MAP(SLEEP)    /* System Sleep */

KEYTABLE_END

#undef VIRTUALKEY_KEY_MAP
#undef VIRTUALKEY_KEY_MAP2
#undef NORMALKEY_KEY_MAP
#undef KEYTABLE_START
#undef KEYTABLE_END